apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  labels:
    name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-volume
    - name: jenkins-container
      image: jenkins:2.60.3
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-volume
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /Users/lucasrocha/dev/docker/primeiro-volume
        type: DirectoryOrCreate
